// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2LgSbZYXoSv5jcMQldF6zPeQ4YJdDCt8',
    appId: '1:143507377283:web:aef336a6d136fbe8b25fb6',
    messagingSenderId: '143507377283',
    projectId: 'vmgrand-b3c47',
    authDomain: 'vmgrand-b3c47.firebaseapp.com',
    storageBucket: 'vmgrand-b3c47.appspot.com',
    measurementId: 'G-0HT5QQEN8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWVOQ-2JXvUXCdiskGyv3PgS7C2xzkq4M',
    appId: '1:143507377283:android:d27917446ff4d101b25fb6',
    messagingSenderId: '143507377283',
    projectId: 'vmgrand-b3c47',
    storageBucket: 'vmgrand-b3c47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtiOeqV0_M4RYQfB_30qsVwyoo-tbVEk8',
    appId: '1:143507377283:ios:71bc622b4c661b17b25fb6',
    messagingSenderId: '143507377283',
    projectId: 'vmgrand-b3c47',
    storageBucket: 'vmgrand-b3c47.appspot.com',
    iosClientId: '143507377283-9va55tr8qpu9il67dfv649l0rh4qj3ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.vmg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtiOeqV0_M4RYQfB_30qsVwyoo-tbVEk8',
    appId: '1:143507377283:ios:240969bf3bcd6d15b25fb6',
    messagingSenderId: '143507377283',
    projectId: 'vmgrand-b3c47',
    storageBucket: 'vmgrand-b3c47.appspot.com',
    iosClientId: '143507377283-uibe0eqqf4htlreg2l3g81bng5ejh4ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.vmg.RunnerTests',
  );
}
